<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36411" started-at="2019-12-11T13:36:58Z" finished-at="2019-12-11T13:37:35Z">
    <groups>
      <group name="admin">
        <method signature="FrameworkRegressionTest.TC3()[pri:5, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC3" class="testng.FrameworkRegressionTest"/>
        <method signature="FrameworkRegressionTest.TC4()[pri:6, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC4" class="testng.FrameworkRegressionTest"/>
      </group> <!-- admin -->
      <group name="Login">
        <method signature="FrameworkRegressionTest.TC2_1()[pri:1, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_1" class="testng.FrameworkRegressionTest"/>
        <method signature="FrameworkRegressionTest.TC2_2()[pri:2, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_2" class="testng.FrameworkRegressionTest"/>
        <method signature="FrameworkRegressionTest.TC2_3()[pri:3, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_3" class="testng.FrameworkRegressionTest"/>
        <method signature="FrameworkRegressionTest.TC2_4()[pri:4, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_4" class="testng.FrameworkRegressionTest"/>
      </group> <!-- Login -->
    </groups>
    <test name="Default test" duration-ms="36411" started-at="2019-12-11T13:36:58Z" finished-at="2019-12-11T13:37:35Z">
      <class name="testng.FrameworkRegressionTest">
        <test-method status="FAIL" signature="TC2_1()[pri:1, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_1" duration-ms="7731" started-at="2019-12-11T13:36:58Z" finished-at="2019-12-11T13:37:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [rOrangeHRM] but found [OrangeHRM]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [rOrangeHRM] but found [OrangeHRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testng.FrameworkRegressionTest.TC2_1(FrameworkRegressionTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_1 -->
        <test-method status="PASS" signature="TC2_2()[pri:2, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_2" duration-ms="13438" started-at="2019-12-11T13:37:06Z" finished-at="2019-12-11T13:37:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_2 -->
        <test-method status="PASS" signature="TC2_3()[pri:3, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_3" duration-ms="8091" started-at="2019-12-11T13:37:19Z" finished-at="2019-12-11T13:37:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_3 -->
        <test-method status="PASS" signature="TC2_4()[pri:4, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC2_4" duration-ms="7093" started-at="2019-12-11T13:37:27Z" finished-at="2019-12-11T13:37:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC2_4 -->
        <test-method status="SKIP" signature="TC3()[pri:5, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC3" duration-ms="0" started-at="2019-12-11T13:37:35Z" depends-on-methods="testng.FrameworkRegressionTest.TC2_1" finished-at="2019-12-11T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method FrameworkRegressionTest.TC3()[pri:5, instance:testng.FrameworkRegressionTest@5b275dab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method FrameworkRegressionTest.TC3()[pri:5, instance:testng.FrameworkRegressionTest@5b275dab] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method status="SKIP" signature="TC4()[pri:6, instance:testng.FrameworkRegressionTest@5b275dab]" name="TC4" duration-ms="0" started-at="2019-12-11T13:37:35Z" depends-on-methods="testng.FrameworkRegressionTest.TC2_1" finished-at="2019-12-11T13:37:35Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method FrameworkRegressionTest.TC4()[pri:6, instance:testng.FrameworkRegressionTest@5b275dab] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method FrameworkRegressionTest.TC4()[pri:6, instance:testng.FrameworkRegressionTest@5b275dab] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC4 -->
      </class> <!-- testng.FrameworkRegressionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
